import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  {
    name: 'Produit 1',
    slug: toSlug('Produit 1'),
    category: 'Ongles',
    images: ['/images/p1.1.jpg', '/images/p1.2.jpg', '/images/p1.3.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description:
      'Ce produit vous ira à ravir, idéal pour vos entretiens d embauche',
    reviews: [],
  },
  {
    name: 'Produit 2',
    slug: toSlug('Produit 2'),
    category: 'Ongles',
    images: ['/images/p2.1.jpg', '/images/p2.2.jpg', '/images/p2.3.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description: 'Ce produit vous ira à ravir, idéal pour votre mariage',
    reviews: [],
  },
  {
    name: 'Produit 3',
    slug: toSlug('Produit 3'),
    category: 'Ongles',
    images: ['/images/p3.1.jpg', '/images/p3.2.jpg', '/images/p3.3.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description: 'Ce produit vous ira à ravir, idéal pour votre date',
    reviews: [],
  },
  {
    name: 'Produit 4',
    slug: toSlug('Produit 4'),
    category: 'Ongles',
    images: ['/images/p4.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description:
      'Ce produit vous ira à ravir, idéal pour vos sorties entre amies',
    reviews: [],
  },
  {
    name: 'Produit 5',
    slug: toSlug('Produit 5'),
    category: 'Ongles',
    images: ['/images/p5.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description:
      'Ce produit vous ira à ravir, idéal pour vos photos instagrams',
    reviews: [],
  },
  {
    name: 'Produit 6',
    slug: toSlug('Produit 6'),
    category: 'Ongles',
    images: ['/images/p6.jpg'],
    tags: ['nouveautes'],
    isPublished: true,
    price: 40.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    description: 'Ce produit vous ira à ravir, idéal pour le cocooning',
    reviews: [],
  },
]
const data: Data = {
  headerMenus: [
    {
      name: 'Soldes',
      href: '/search?tag=soldes',
    },
    {
      name: 'Nouveautés',
      href: '/search?tag=nouveautes',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Personnalisables',
      href: '/search?tag=personnalisables',
    },
  ],
  carousels: [
    {
      title: 'Bienvenue sur Oxygemstudio',
      buttonCaption: 'Acheter',
      image: '/images/banner31a.jpg',
      url: '/search?category=Ongles',
      isPublished: true,
    },
    {
      title: 'Nouvel An Chinois',
      buttonCaption: 'Acheter maintenant',
      image: '/images/banner21.jpg',
      url: '/search?category=Ongles',
      isPublished: true,
    },
    {
      title: 'Rouge Gold',
      buttonCaption: 'Acheter maintenant',
      image: '/images/banner11.png',
      url: '/search?category=Ongles',
      isPublished: true,
    },
  ],
  products,
}

export default data
